theme: jekyll-theme-slate
title: Hong Kong Electronics Technology Professionals' Union
description: A Union of professionals specialized in design or development of electronics technology in Hong Kong
